config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stocks
  resources :items
  get 'home/about'
  get 'home/contact'
  get 'home/services'
  get 'home/login'
    get 'home/signup'
  #root'home#index'
  root'stocks#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many:stocks
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about_me = "my name is destiny"
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
      @contact_me = "my name is destiny"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def login
  end
  def Signup
  end
  def about
    @about_me = ""

  end
  def contact
      @contact_me = ""
  end
  def Service
      @service_me = ""
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.fetch(:item, {})
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
      @service_me = "my name is destiny"
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action  :authenticate_user!, except: [:index,:show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    #@stock = Stock.new
    @stock = current_user.stocks.build
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    #@stock = Stock.new(stock_params)
  @stock = current_user.stocks.build(stock_params)
    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end
def correct_user
  @stock =current_user.stocks.find_by(id: params[:id])
  redirect_to stocks_path, notice:"Not Authorized To Edit This stock" if @stock.nil?
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:stock_name, :stock_id, :status, :user_id)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Shopify', root_path, class:"navbar-brand"%>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'About us', home_about_path, class:"nav-link"%>

      </li>

          <li class="nav-item active">
            <%= link_to 'Contact us', home_contact_path, class:"nav-link"%>

          </li>

              <li class="nav-item active">
                <%= link_to 'Services', home_services_path, class:"nav-link"%>

              </li>


                    

<%if user_signed_in?%>

                          </li>
                          <li class="nav-item active">
                            <%= link_to 'sign out',  destroy_user_session_path, method: :delete ,class:"nav-link"%>

                          </li>


                                                    <li class="nav-item active">
                                                      <%= link_to 'edit profile',  edit_user_registration_path, class:"nav-link"%>

                                                    </li>
                                                  </li>

                                                      <li class="nav-item active">
                                                        <%= link_to 'Add stock', new_stock_path, class:"nav-link"%>
                                                        </li>

<%else%>

                          <li class="nav-item active">
                            <%= link_to 'sign up',  new_user_registration_path, class:"nav-link"%>

                          </li>

                          <li class="nav-item active">
                            <%= link_to 'sign in', new_user_session_path, class:"nav-link"%>
<%end%>








    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>About</title>
<link rel="stylesheet" href="">
 <h1> </h1>

  </head>
  <body>

<h1>about us</h1>
<p>
<%= @about_me%>
</p>



  </body>
  <footer>
  </footer>
</html>

app/views/home/contact.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>Contact</title>
<link rel="stylesheet" href="">
 <h1> </h1>

  </head>
  <body>
<h1> contact us</h1>

<p> @contact_me </p>



  </body>
  <footer>
  </footer>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>Home</title>
<link rel="stylesheet" href="">
 <h1> </h1>

  </head>
  <body>
















<p> Welcome</p>



  </body>
  <footer>
  </footer>
</html>

app/views/home/login.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>login</title>
    <link rel="stylesheet" href="">
  </head>
  <body>
    <div class="site-logo">
      <img src="logo.png" alt=logo width="300px">
    </div>

    <form action="/signup" method="post" name="login">
        <fieldset>



<label for="username">  username

</label><br>
<input type="text" id="username" placeholder="username">
<br>
<label for="password"> password

</label><br>
<input type="password" placeholder="password" id="password"><br>

 <label for="gender"> <input type="checkbox" name="remember" >
stay signed in
 </label><br>
 <a href="index.html"/>
<input type="button" name="signup" value="signup">
</a><br>
<a href="home5.html"/>
<input type="button" type="submit" value="login"/>
</a>
</fieldset>
    </form>

<script src="login.js"></script>


  </body>
</html>

app/views/home/services.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>Services</title>
<link rel="stylesheet" href="">
 <h1> </h1>

  </head>
  <body>

<h1> Services</h1>


<p> @service_me</p>



  </body>
  <footer>
  </footer>
</html>

app/views/home/signup.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Signup</title>
    <link rel="stylesheet" href="">
  </head>
  <body>
    <div class="site-logo">
      <img src="logo3.png" alt=logo width="300px">
    </div>
    <form action="/signup" method="post"name="signup">
        <fieldset>
          <div>
<label for="firstname">  firstname
  <input type=" text" id="  firstname"placeholder="firstname">
</label>
<span id ="name-error"></span>
<br>
<label for="surname">  surname
  <input type="text"  id=" surname" placeholder="surname">

</label>
<span id ="name-error"></span>
<br>
<label for="username">  username
<input type="text" id="username" placeholder="username">
</label>
<span id ="username-error"></span>
<br>
<label for="password">  password
  <input type="password" placeholder="password" id="password">
</label>
<span id="password-error"></span><br>
<label for="email">  email
  <input type="email" id="email" placeholder="email">
</label>
<span id="email-error"></span>
<br>
<label for="phone">number
  <input type="tel" id="phone" name="phone"placeholder="phone number">
 </label>
<span id="phone-error"></span>
 <br>
 <label for="gender"> enter your gender
<label for="Male">   <input type="radio" name="gender" value="Male" id="Male"> Male</label>
  <label for="Female" ><input type="radio" name="gender" value="Female" id="Female">Female</label>
  <label for="other"> <input type="radio" name="gender" value="other"id="other">other</label>
<span id="gender-error"></span>
 </label><br>
 <a href="login.html">
<input type="button" name="login" value="login">
</a><br>
<input  type="submit" value="done"/>
<span id="done-error"></span>
</div>
</fieldset>
    </form>

<script src="index.js"></script>
  </body>
</html>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>

  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
<%= render 'home/header'%>
<br>
<%if notice%>
<%= render 'layouts/alerts'%>
<%end%>
  <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% form.label :stock_name, style: "display: block" %>
    <%= form.text_field :stock_name ,class:"form-control"  ,placeholder:"stock name"%>
  </div>

  <div class="form-group">
    <% form.label :stock_amount, style: "display: block" %>
    <%= form.text_field :stock_id ,class:"form-control", placeholder:"amount of stock" %>
  </div>

  <div class="form-group">
    <% form.label :status, style: "display: block" %>
    <%= form.text_field :status ,class:"form-control",placeholder:"status" %>
  </div>
  <div class="form-group">
    <% form.label :status, style: "display: block" %>
    <%= form.number_field :user_id,id: :stock_user_id ,class:"form-control",value:current_user.id,type: :hidden %>
  </div>

  <div >
    <%= form.submit  class:'btn btn-dark'%>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
  <p>
    <strong>Stock name:</strong>
    <%= stock.stock_name %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= stock.stock_amount %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= stock.status %>
  </p>


</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>
<table class="table">
<%= render "form", stock: @stock %>
</table>

</table>
<br>

<div>
  <%= link_to "Show ", @stock,class:"btn btn-dark" %> |
  <%= link_to "Back ", stocks_path,class:"btn btn-dark" %>
  <%= button_to "Delete", @stock, method: :delete ,class:"btn btn-dark" %>

</div>

app/views/stocks/index.html.erb
<%if user_signed_in? %>
<h1>Stocks</h1>

<div id="stocks">
  <% @stocks.each do |stock| %>
  <% if stock.user == current_user%>

    <%= render stock %>
    <p>
      <%= link_to "Show ", stock, class:"btn btn-dark" %>
    </p>
  <% end %>
    <% end %>
</div>

<%= link_to "New stock", new_stock_path, class:"btn btn-dark" %>
<% else%>
<h1> Welcome</h1>
<%end%>

app/views/stocks/new.html.erb
<h1> Add New stock</h1>
<br>
<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back ", stocks_path ,class:"btn btn-dark"%>
</div>

app/views/stocks/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= render @stock %></h1>

    <div>
      <%= link_to "Edit ", edit_stock_path(@stock) ,class:"btn btn-dark"%>
      <%= link_to "Back ", stocks_path, class:"btn btn-dark" %>
<%= button_to "Delete", @stock, method: :delete ,class:"btn btn-dark" %>
    </div>
  </p>
</div>